### ISSUE TITLE
Hardcoded VEHICLE_ID

### ISSUE THREAD

**Issue by ebadi** [ebadi/ScenarioGenerator#5]
As you seen in `https://github.com/ebadi/ScenarioGenerator/blob/master/Simulation.py`, the following vehicle ID is hard coded. 

```
EGO_VEHICLE_ID = "8d60a6ac-65a4-4bc5-8fc5-870156b6608f"
```

I am not sure if the configuration that I made in `https://wise.svlsimulator.com` is accessible to other users. The process is described in the presentation (see below). **Please watch these videos.**
http://av-test-challenge.org/meetings.html 

1) create a new **Lincoln2017MKZ** vehicle

2) update your configuration using web interface(see the video). Have in mind that your configuration file may be different from mine. 
[Lincoln2017MKZ_config.json](https://github.com/ebadi/ScenarioGenerator/blob/master/Lincoln2017MKZ_config.json)

3) extract your unique vehicle ID: 
![image](https://user-images.githubusercontent.com/1111940/167909813-8e924d8e-cc42-4d65-9746-0f695ba42d22.png)

Click on ID 
![image](https://user-images.githubusercontent.com/1111940/167909962-d8a5e585-064a-4fc0-85eb-64bcacfe82a9.png)

**Comment by JasonBourne1998** [comment]
> As you seen in `https://github.com/ebadi/ScenarioGenerator/blob/master/Simulation.py`, the following vehicle ID is hard coded.
> 
> ```
> EGO_VEHICLE_ID = "8d60a6ac-65a4-4bc5-8fc5-870156b6608f"
> ```
> 
> I am not sure if the configuration that I made in `https://wise.svlsimulator.com` is accessible to other users. The process is described in the presentation (see below). **Please watch these videos.** http://av-test-challenge.org/meetings.html
> 
> 1. create a new **Lincoln2017MKZ** vehicle
> 2. update your configuration using web interface(see the video). Have in mind that your configuration file may be different from mine.
>    [Lincoln2017MKZ_config.json](https://github.com/ebadi/ScenarioGenerator/blob/master/Lincoln2017MKZ_config.json)
> 3. extract your unique vehicle ID:
>    ![image](https://user-images.githubusercontent.com/1111940/167909813-8e924d8e-cc42-4d65-9746-0f695ba42d22.png)
> 
> Click on ID ![image](https://user-images.githubusercontent.com/1111940/167909962-d8a5e585-064a-4fc0-85eb-64bcacfe82a9.png)

Hi @ebadi , thanks for your reply. But I have one more question with your configuration. I notice that there is neither lidar nor ridar in the sensor list, so how could you detect the pedestrain in your dreamview?
![image](https://user-images.githubusercontent.com/51346614/168144211-c1fc746f-1d08-47a8-9f9b-eceb927d4ef9.png)

**Comment by ebadi** [comment]
Please watch the video. It was the configuration that the competition requested us to use.

**Comment by JasonBourne1998** [comment]
> Please watch the video. It was the configuration that the competition requested us to use.

Thanks! another question :), when the collison happen, and I want to replay the collision, so I input the noise vector and corresponding json result to the replay.sh, but the collision did not happen again in simulator. I think it is maybe caused by the unstable of the dreamview? Have you solved the replay collision problem? 

![image](https://user-images.githubusercontent.com/51346614/168224470-78e62588-990c-46e1-9395-692ccd5689ae.png)
![image](https://user-images.githubusercontent.com/51346614/168224514-a433d926-83a2-464b-9edb-19dd97e78b92.png)

**Comment by ebadi** [comment]
We had the same issue, and we reported this.
See https://github.com/lgsvl/simulator/issues/1548.
@JasonBourne1998  Please open a new issue if your question is not related to the main topic of the issue. This makes it easier for other to find their answers as well. Thanks

**Comment by GiantSeaweed** [comment]
> Please watch the video. It was the configuration that the competition requested us to use.

This link seems broken. Anywhere else to watch those videos? 

Currently I am stuck on correctly loading the config file for sensors. Thanks!

Specifically, I just changed the hard-coded EGO ID. And my error msg is:

```
Traceback (most recent call last):
  File "/home/feng292/ScenarioGenerator/Simulation.py", line 257, in execute
    self.initiate_simulator()
  File "/home/feng292/ScenarioGenerator/Simulation.py", line 201, in initiate_simulator
    self.agents[ego_indx] = self.sim.add_agent(EGO_VEHICLE_ID, lgsvl.AgentType.EGO, self.init_ego_state )
  File "/home/feng292/PythonAPI/lgsvl/utils.py", line 23, in new_f
    return f(*args, **kwargs)
  File "/home/feng292/PythonAPI/lgsvl/simulator.py", line 164, in add_agent
    uid = self.remote.command("simulator/add_agent", args)
  File "/home/feng292/PythonAPI/lgsvl/remote.py", line 69, in command
    raise Exception(data["error"])
Exception: Issue loading sensor type CanBusSensor for gameobject Lincoln2017MKZ check logs
```
